# Generated by Django 4.2.7 on 2025-10-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
