# Generated by Django 5.2.4 on 2025-08-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_areaofactivity_emailwebsite_socialmedia_tag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areaofactivity",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="areaofduty",
            name="dutie_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="core",
            name="core_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="popup",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="popup",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="popup",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name_tag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="typeofservice",
            name="service_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="cep",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="district",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("acre", "Acre"),
                    ("alagoas", "Alagoas"),
                    ("amapa", "Amapá"),
                    ("amazonas", "Amazonas"),
                    ("bahia", "Bahia"),
                    ("ceara", "Ceará"),
                    ("distrito_federal", "Distrito Federal"),
                    ("espirito_santo", "Espírito Santo"),
                    ("goias", "Goiás"),
                    ("maranhao", "Maranhão"),
                    ("mato_grosso", "Mato Grosso"),
                    ("mato_grosso_do_sul", "Mato Grosso do Sul"),
                    ("minas_gerais", "Minas Gerais"),
                    ("para", "Pará"),
                    ("paraiba", "Paraíba"),
                    ("parana", "Paraná"),
                    ("pernambuco", "Pernambuco"),
                    ("piaui", "Piauí"),
                    ("rio_de_janeiro", "Rio de Janeiro"),
                    ("rio_grande_do_norte", "Rio Grande do Norte"),
                    ("rio_grande_do_sul", "Rio Grande do Sul"),
                    ("rondonia", "Rondônia"),
                    ("roraima", "Roraima"),
                    ("santa_catarina", "Santa Catarina"),
                    ("sao_paulo", "São Paulo"),
                    ("sergipe", "Sergipe"),
                    ("tocantins", "Tocantins"),
                ],
                default="santa_catarina",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="street",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="unit_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="websiteinformations",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
