# Generated by Django 5.2.4 on 2025-08-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_areaofactivity_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmedia",
            name="name",
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("facebook", "Facebook"),
                    ("x", "X"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                    ("linkedin", "LinkedIn"),
                    ("pinterest", "Pinterest"),
                    ("vimeo", "Vimeo"),
                ],
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
