# Generated by Django 5.2.4 on 2025-08-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_socialmedia_name_alter_socialmedia_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmedia",
            name="icon",
        ),
        migrations.RemoveField(
            model_name="socialmedia",
            name="url",
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="facebook",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="instagram",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="linkedin",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="pinterest",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="vimeo",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="x",
            field=models.URLField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="youtube",
            field=models.URLField(blank=True, default="", null=True),
        ),
    ]
