# Generated by Django 5.2.4 on 2025-08-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_socialmedia_icon_remove_socialmedia_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="socialmedia",
            old_name="facebook",
            new_name="url",
        ),
        migrations.RemoveField(
            model_name="socialmedia",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="socialmedia",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="socialmedia",
            name="pinterest",
        ),
        migrations.RemoveField(
            model_name="socialmedia",
            name="vimeo",
        ),
        migrations.RemoveField(
            model_name="socialmedia",
            name="x",
        ),
        migrations.RemoveField(
            model_name="socialmedia",
            name="youtube",
        ),
        migrations.AddField(
            model_name="socialmedia",
            name="network",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("x", "X"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                    ("linkedin", "LinkedIn"),
                    ("pinterest", "Pinterest"),
                    ("vimeo", "Vimeo"),
                ],
                default="facebook",
                max_length=20,
                unique=True,
            ),
        ),
    ]
