# Generated by Django 5.2.4 on 2025-09-04 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_rename_facebook_socialmedia_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailwebsite",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email_website", "Email do Website"),
                    ("comentarios", "Comentários"),
                    ("faq", "FAQ"),
                    ("relato_de_erros", "Relato de Erros"),
                ],
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="network",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("x", "X"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                    ("linkedin", "LinkedIn"),
                    ("pinterest", "Pinterest"),
                    ("vimeo", "Vimeo"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.RemoveField(
            model_name="unit",
            name="area_of_duty",
        ),
        migrations.CreateModel(
            name="UnitService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schedules", models.TextField(blank=True, null=True)),
                (
                    "type_of_service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.typeofservice",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="core.unit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="unit",
            name="area_of_duty",
            field=models.ManyToManyField(blank=True, to="core.areaofduty"),
        ),
    ]
