# Generated by Django 5.2.4 on 2025-09-15 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_news_newsattachment_newsgallery"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NewsGallery",
            new_name="NewsGalleryImage",
        ),
    ]
