# Generated by Django 5.2.4 on 2025-09-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_rename_newsgallery_newsgalleryimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsattachment",
            name="file",
            field=models.FileField(upload_to="news/attachments/"),
        ),
        migrations.AlterField(
            model_name="newsgalleryimage",
            name="image",
            field=models.ImageField(upload_to="news/gallery/"),
        ),
    ]
