# Generated by Django 5.2.4 on 2025-09-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_newsattachment_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
