# Generated by Django 5.2.4 on 2025-09-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_news_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="url",
        ),
        migrations.AddField(
            model_name="news",
            name="subtitle",
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
