# Generated by Django 5.2.4 on 2025-09-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_remove_news_url_news_subtitle_alter_news_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="tags",
            field=models.ManyToManyField(blank=True, null=True, to="core.tag"),
        ),
    ]
