# Generated by Django 5.2.4 on 2025-09-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_alter_news_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="tags",
            field=models.ManyToManyField(blank=True, to="core.tag"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                error_messages={"unique": "Já existe uma notícia com este título."},
                max_length=255,
                unique=True,
            ),
        ),
    ]
