# Generated by Django 5.2.4 on 2025-09-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_news_tags_alter_news_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name_tag",
            field=models.CharField(
                blank=True,
                error_messages={"unique": "Já existe uma tag com este nome."},
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
