# Generated by Django 5.2.4 on 2025-09-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_alter_tag_name_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areaofactivity",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Publicado"),
                    ("not_published", "Não publicado"),
                    ("scheduled", "Agendado"),
                ],
                default="not_published",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="areaofduty",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Publicado"),
                    ("not_published", "Não publicado"),
                    ("scheduled", "Agendado"),
                ],
                default="not_published",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Publicado"),
                    ("not_published", "Não publicado"),
                    ("scheduled", "Agendado"),
                ],
                default="not_published",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="core",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Publicado"),
                    ("not_published", "Não publicado"),
                    ("scheduled", "Agendado"),
                ],
                default="not_published",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emailwebsite",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Publicado"),
                    ("not_published", "Não publicado"),
                    ("scheduled", "Agendado"),
                ],
                default="not_published",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Publicado"),
                    ("not_published", "Não publicado"),
                    ("scheduled", "Agendado"),
                ],
                default="not_published",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Publicado"),
                    ("not_published", "Não publicado"),
                    ("scheduled", "Agendado"),
                ],
                default="not_published",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="popup",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Publicado"),
                    ("not_published", "Não publicado"),
                    ("scheduled", "Agendado"),
                ],
                default="not_published",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Publicado"),
                    ("not_published", "Não publicado"),
                    ("scheduled", "Agendado"),
                ],
                default="not_published",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Publicado"),
                    ("not_published", "Não publicado"),
                    ("scheduled", "Agendado"),
                ],
                default="not_published",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="typeofservice",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Publicado"),
                    ("not_published", "Não publicado"),
                    ("scheduled", "Agendado"),
                ],
                default="not_published",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Publicado"),
                    ("not_published", "Não publicado"),
                    ("scheduled", "Agendado"),
                ],
                default="not_published",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="websiteinformations",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Publicado"),
                    ("not_published", "Não publicado"),
                    ("scheduled", "Agendado"),
                ],
                default="not_published",
                max_length=20,
            ),
        ),
    ]
