# Generated by Django 4.2.7 on 2025-10-01 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_subcategory_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="records",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="core.category",
            ),
        ),
        migrations.AlterField(
            model_name="records",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="core.subcategory",
            ),
        ),
    ]
