# Generated by Django 4.2.7 on 2025-10-08 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0027_records_category_alter_records_sub_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.CreateModel(
            name="Posters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Publicado"),
                            ("not_published", "Não publicado"),
                            ("scheduled", "Agendado"),
                        ],
                        default="not_published",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "title",
                    models.CharField(
                        error_messages={
                            "unique": "Já existe uma cartilha com este título."
                        },
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="posters/images/")),
                ("attachment", models.FileField(upload_to="posters/attachments/")),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
