# Generated by Django 4.2.7 on 2025-10-15 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_news_slug_posters"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.subcategory",
            ),
        ),
    ]
