# Generated by Django 4.2.7 on 2025-10-14 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0030_cards_cardregister"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Publicado"),
                            ("not_published", "Não publicado"),
                            ("scheduled", "Agendado"),
                        ],
                        default="not_published",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("banner", models.ImageField(upload_to="banner/images/")),
                ("slug", models.CharField(blank=True, max_length=255, null=True)),
                ("alt", models.TextField(blank=True)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("slides", "Slides"),
                            ("footer_banner", "Banner do rodapé"),
                        ],
                        max_length=255,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="banner",
            constraint=models.UniqueConstraint(
                condition=models.Q(("group", "footer_banner")),
                fields=("group",),
                name="unique_footer_banner",
            ),
        ),
    ]
