# Generated by Django 4.2.7 on 2025-10-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_cards_cardregister"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cardregister",
            name="page",
        ),
        migrations.AddField(
            model_name="cardregister",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="cards/images/"),
        ),
        migrations.AddField(
            model_name="cardregister",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
