# Generated by Django 4.2.7 on 2025-10-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_banner_banner_unique_footer_banner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={"ordering": ["position"]},
        ),
        migrations.AddField(
            model_name="banner",
            name="banner_mobile",
            field=models.ImageField(blank=True, null=True, upload_to="banner/images/"),
        ),
        migrations.AlterField(
            model_name="banner",
            name="position",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
