# Generated by Django 4.2.7 on 2025-10-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_remove_cardregister_page_cardregister_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardregister",
            name="slug",
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
    ]
