# Generated by Django 4.2.7 on 2025-10-16 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_subcategory_sub_category"),
        ("core", "0032_cardregister_slug"),
    ]

    operations = []
