# Generated by Django 4.2.7 on 2025-10-15 16:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_banner_options_banner_banner_mobile_and_more"),
        ("core", "0032_cardregister_slug"),
    ]

    operations = []
