# Generated by Django 4.2.7 on 2025-10-20 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_merge_20251016_1715"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardregister",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registers",
                to="core.cards",
            ),
        ),
    ]
