# Generated by Django 4.2.7 on 2025-10-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_container"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="show_title",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="container",
            name="title",
            field=models.CharField(default="Título Padrão", max_length=255),
        ),
    ]
