# Generated by Django 4.2.7 on 2025-10-20 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_merge_20251016_1715"),
        ("core", "0036_servicebuttons"),
    ]

    operations = []
