# Generated by Django 4.2.7 on 2025-10-20 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0037_merge_0033_merge_20251016_1715_0036_servicebuttons"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickAccessButtons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Publicado"),
                            ("not_published", "Não publicado"),
                            ("scheduled", "Agendado"),
                        ],
                        default="not_published",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "title_color",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("image", models.ImageField(upload_to="quick_access/images/")),
                (
                    "background_color",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("above_group", "Grupo de cima"),
                            ("under_group", "Grupo de baixo"),
                        ],
                        max_length=255,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=1)),
                ("link", models.CharField(max_length=255)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
