# Generated by Django 4.2.7 on 2025-10-20 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_alter_cardregister_card"),
        ("core", "0038_quickaccessbuttons"),
    ]

    operations = []
