# Generated by Django 4.2.7 on 2025-10-20 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_merge_20251020_1523"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.cards",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.category",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="has_cores",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="page",
            name="has_faq",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="page",
            name="has_news",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="page",
            name="has_posters",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="quickaccessbuttons",
            name="group",
            field=models.CharField(
                choices=[
                    ("above_group", "Parte superior"),
                    ("under_group", "Parte inferior"),
                ],
                max_length=255,
            ),
        ),
    ]
