# Generated by Django 4.2.7 on 2025-10-21 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0040_page_card_page_category_page_has_cores_page_has_faq_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"permissions": [("can_create_page", "Pode criar páginas")]},
        ),
        migrations.AddField(
            model_name="page",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="manageable_pages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuários com permissão para editar/excluir esta página",
            ),
        ),
    ]
