# Generated by Django 4.2.7 on 2025-10-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_alter_page_options_page_allowed_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmedia",
            name="network",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("x", "X"),
                    ("instagram", "Instagram"),
                    ("youtube", "YouTube"),
                    ("linkedin", "LinkedIn"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
    ]
