# Generated by Django 4.2.7 on 2025-10-23 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_alter_page_options_page_allowed_users"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={},
        ),
        migrations.RemoveField(
            model_name="page",
            name="allowed_users",
        ),
    ]
