# Generated by Django 4.2.7 on 2025-10-30 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_page_path"),
        ("core", "0042_header"),
    ]

    operations = []
