# Generated by Django 4.2.7 on 2025-10-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_merge_0002_page_path_0042_header"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardregister",
            name="path",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cards",
            name="path",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="path",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="posters",
            name="path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
