# Generated by Django 4.2.7 on 2025-10-31 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_merge_0002_page_path_0042_header"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="cep",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="unit",
            name="city",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="unit",
            name="district",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="unit",
            name="state",
            field=models.CharField(
                choices=[
                    ("acre", "Acre"),
                    ("alagoas", "Alagoas"),
                    ("amapa", "Amapá"),
                    ("amazonas", "Amazonas"),
                    ("bahia", "Bahia"),
                    ("ceara", "Ceará"),
                    ("distrito_federal", "Distrito Federal"),
                    ("espirito_santo", "Espírito Santo"),
                    ("goias", "Goiás"),
                    ("maranhao", "Maranhão"),
                    ("mato_grosso", "Mato Grosso"),
                    ("mato_grosso_do_sul", "Mato Grosso do Sul"),
                    ("minas_gerais", "Minas Gerais"),
                    ("para", "Pará"),
                    ("paraiba", "Paraíba"),
                    ("parana", "Paraná"),
                    ("pernambuco", "Pernambuco"),
                    ("piaui", "Piauí"),
                    ("rio_de_janeiro", "Rio de Janeiro"),
                    ("rio_grande_do_norte", "Rio Grande do Norte"),
                    ("rio_grande_do_sul", "Rio Grande do Sul"),
                    ("rondonia", "Rondônia"),
                    ("roraima", "Roraima"),
                    ("santa_catarina", "Santa Catarina"),
                    ("sao_paulo", "São Paulo"),
                    ("sergipe", "Sergipe"),
                    ("tocantins", "Tocantins"),
                ],
                default="santa_catarina",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="street",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="unit",
            name="types_of_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.typeofservice",
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="unit_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
