# Generated by Django 4.2.7 on 2025-11-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_alter_unit_cep_alter_unit_city_alter_unit_district_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
