# Generated by Django 4.2.7 on 2025-11-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_cardregister_path_cards_path_news_path_posters_path"),
        ("core", "0045_alter_contact_phone_alter_email_email"),
    ]

    operations = []
