# Generated by Django 4.2.7 on 2025-11-04 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_merge_20251103_1522"),
    ]

    operations = [
        migrations.RenameField(
            model_name="container",
            old_name="redirect_button",
            new_name="external_link",
        ),
        migrations.AddField(
            model_name="container",
            name="internal_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Página interna",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="containers",
                to="core.page",
            ),
        ),
    ]
