# Generated by Django 4.2.7 on 2025-11-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_rename_redirect_button_container_external_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("internal", "Interno"), ("external", "Externo")],
                max_length=255,
                null=True,
            ),
        ),
    ]
