# Generated by Django 4.2.7 on 2025-11-05 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_container_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="internal_link",
            field=models.ForeignKey(
                blank=True,
                help_text="Página interna",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="containers",
                to="core.page",
            ),
        ),
    ]
